#!/usr/bin/env python3
"""Regenerate firmware assets after editing web/*. No filesystem upload needed."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
parts = ['#pragma once\n#include <Arduino.h>\n// Generated by tools/embed_web.py; no CDN or external dependencies.\n']
for symbol, name in [('WEB_HTML', 'index.html'), ('WEB_CSS', 'app.css'), ('WEB_JS', 'app.js')]:
    text = (root / 'web' / name).read_text(encoding='utf-8')
    if ')HHRWEB"' in text:
        raise ValueError('Raw-string delimiter collision')
    parts.append(f'static const char {symbol}[] PROGMEM = R"HHRWEB({text})HHRWEB";\n')
(root / 'HackHeld_BLE_Remote' / 'WebAssets.h').write_text(''.join(parts), encoding='utf-8')
